<a href="https://colab.research.google.com/github/imbuoyp/Python-Data/blob/main/Pytorch_%EC%8B%A4%EC%8A%B5(1)_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline


What is PyTorch?
================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

-  NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
-  최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Getting Started
---------------

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.



In [1]:
from __future__ import print_function
import torch

초기화되지 않은 5x3 행렬을 생성합니다:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[4.4247e-36, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3788e-14, 1.8369e+28, 1.9433e-19],
        [3.3738e-12, 7.4086e+28, 6.9397e+22],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])


무작위로 초기화된 행렬을 생성합니다:



In [4]:
x = torch.randn(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[-0.1566, -0.0730,  0.3119],
        [-1.3005, -0.5426,  0.2618],
        [ 0.6927,  0.1264, -1.6748],
        [-0.6294, -0.4030,  0.1020],
        [-0.0214, -1.4461, -0.3438]])
tensor([[0.1652, 0.0269, 0.0342],
        [0.2191, 0.5144, 0.8676],
        [0.8620, 0.1251, 0.9995],
        [0.0643, 0.4369, 0.6353],
        [0.6726, 0.3111, 0.4163]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 tensor를 직접 생성합니다:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.


In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0695, -0.3980,  0.9388],
        [ 0.2012, -0.4168,  0.2019],
        [ 0.0352,  0.7859,  0.1839],
        [-0.4859, -0.1883,  0.2783],
        [ 0.4508,  1.5532,  2.5128]])


행렬의 크기를 구합니다:



In [7]:
print(x.size())
print(x.shape)

torch.Size([2])
torch.Size([2])



덧셈: 문법1

In [9]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([5.5000, 3.0000])
tensor([[0.1893, 0.3083, 0.2088],
        [0.7658, 0.0457, 0.1160],
        [0.5955, 0.6502, 0.1668],
        [0.2866, 0.6216, 0.7221],
        [0.7172, 0.6203, 0.5612]])


RuntimeError: ignored

덧셈: 문법2



In [ ]:
print(torch.add(x, y))

tensor([[ 0.2187,  0.1099,  1.7767],
        [ 1.1667, -0.3841,  1.0742],
        [ 0.3515,  1.2320,  0.5419],
        [-0.2865,  0.1081,  0.8990],
        [ 1.3133,  2.3246,  2.8989]])


덧셈: 결과 tensor를 인자로 제공


In [ ]:
result = torch.empty(5, 3)
print(result)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2187,  0.1099,  1.7767],
        [ 1.1667, -0.3841,  1.0742],
        [ 0.3515,  1.2320,  0.5419],
        [-0.2865,  0.1081,  0.8990],
        [ 1.3133,  2.3246,  2.8989]])


덧셈: 바꿔치기(In-place) 방식


In [ ]:
# adds x to y
#설명한 거 추가한부분 print(y)
y.add_(x)
print(y)

tensor([[ 0.2187,  0.1099,  1.7767],
        [ 1.1667, -0.3841,  1.0742],
        [ 0.3515,  1.2320,  0.5419],
        [-0.2865,  0.1081,  0.8990],
        [ 1.3133,  2.3246,  2.8989]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.<p>
예: x.copy_(y), x.t_() 는 x 를 변경합니다.

<p>
NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!


In [ ]:
print(x[:, 1])

tensor([-0.3980, -0.4168,  0.7859, -0.1883,  1.5532])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:


In [ ]:
import torch

x = torch.randn(4, 4)
#수업하면서 타이핑 print(x.shape)
y = x.view(16)
z = x.view(-1, 4)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2037])
-0.20373372733592987


**읽을 거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>` 에 설명되어 있습니다.

NumPy 변환(Bridge)
------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

- Torch Tensor를 NumPy 배열로 변환하기



In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


 - NumPy 배열을 Torch Tensor로 변환하기  
 
NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [ ]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

CUDA Tensors
------------

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [ ]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([0.7963], device='cuda:0')
tensor([0.7963], dtype=torch.float64)
